#enum BadgeColor {
#   BLACK
#   , RED
#   , WHITE
#   , BLUE
#   , PURPLE
#   , GREEN
#   , TOTAL_COLORS
#};

all:
	c++ main.cpp 
	./a.out black.bin 0
	./a.out red.bin 1
	./a.out white.bin 2
	./a.out blue.bin 3
	./a.out purple.bin 4
	./a.out green.bin 5
