#pragma once
uint32_t getWidthcherry();
uint32_t getHeightcherry();
uint32_t getBytePerPixelcherry();
const uint8_t *getPixelDatacherry();
uint32_t getWidthcolor2down();
uint32_t getHeightcolor2down();
uint32_t getBytePerPixelcolor2down();
const uint8_t *getPixelDatacolor2down();
uint32_t getWidthcolor2left();
uint32_t getHeightcolor2left();
uint32_t getBytePerPixelcolor2left();
const uint8_t *getPixelDatacolor2left();
uint32_t getWidthcolor2right();
uint32_t getHeightcolor2right();
uint32_t getBytePerPixelcolor2right();
const uint8_t *getPixelDatacolor2right();
uint32_t getWidthcolor2up();
uint32_t getHeightcolor2up();
uint32_t getBytePerPixelcolor2up();
const uint8_t *getPixelDatacolor2up();
uint32_t getWidthcolor3down();
uint32_t getHeightcolor3down();
uint32_t getBytePerPixelcolor3down();
const uint8_t *getPixelDatacolor3down();
uint32_t getWidthcolor3left();
uint32_t getHeightcolor3left();
uint32_t getBytePerPixelcolor3left();
const uint8_t *getPixelDatacolor3left();
uint32_t getWidthcolor3right();
uint32_t getHeightcolor3right();
uint32_t getBytePerPixelcolor3right();
const uint8_t *getPixelDatacolor3right();
uint32_t getWidthcolor3up();
uint32_t getHeightcolor3up();
uint32_t getBytePerPixelcolor3up();
const uint8_t *getPixelDatacolor3up();
uint32_t getWidthcolordown();
uint32_t getHeightcolordown();
uint32_t getBytePerPixelcolordown();
const uint8_t *getPixelDatacolordown();
uint32_t getWidthcolorleft();
uint32_t getHeightcolorleft();
uint32_t getBytePerPixelcolorleft();
const uint8_t *getPixelDatacolorleft();
uint32_t getWidthcolorright();
uint32_t getHeightcolorright();
uint32_t getBytePerPixelcolorright();
const uint8_t *getPixelDatacolorright();
uint32_t getWidthcolorup();
uint32_t getHeightcolorup();
uint32_t getBytePerPixelcolorup();
const uint8_t *getPixelDatacolorup();
uint32_t getWidtheyedown();
uint32_t getHeighteyedown();
uint32_t getBytePerPixeleyedown();
const uint8_t *getPixelDataeyedown();
uint32_t getWidtheyeleft();
uint32_t getHeighteyeleft();
uint32_t getBytePerPixeleyeleft();
const uint8_t *getPixelDataeyeleft();
uint32_t getWidtheyeright();
uint32_t getHeighteyeright();
uint32_t getBytePerPixeleyeright();
const uint8_t *getPixelDataeyeright();
uint32_t getWidtheyeup();
uint32_t getHeighteyeup();
uint32_t getBytePerPixeleyeup();
const uint8_t *getPixelDataeyeup();
uint32_t getWidthpacman1();
uint32_t getHeightpacman1();
uint32_t getBytePerPixelpacman1();
const uint8_t *getPixelDatapacman1();
uint32_t getWidthpacman2();
uint32_t getHeightpacman2();
uint32_t getBytePerPixelpacman2();
const uint8_t *getPixelDatapacman2();
uint32_t getWidthpacman3();
uint32_t getHeightpacman3();
uint32_t getBytePerPixelpacman3();
const uint8_t *getPixelDatapacman3();
uint32_t getWidthreddown();
uint32_t getHeightreddown();
uint32_t getBytePerPixelreddown();
const uint8_t *getPixelDatareddown();
uint32_t getWidthredleft();
uint32_t getHeightredleft();
uint32_t getBytePerPixelredleft();
const uint8_t *getPixelDataredleft();
uint32_t getWidthredright();
uint32_t getHeightredright();
uint32_t getBytePerPixelredright();
const uint8_t *getPixelDataredright();
uint32_t getWidthredup();
uint32_t getHeightredup();
uint32_t getBytePerPixelredup();
const uint8_t *getPixelDataredup();
uint32_t getWidthstraberry();
uint32_t getHeightstraberry();
uint32_t getBytePerPixelstraberry();
const uint8_t *getPixelDatastraberry();
uint32_t getWidthvulnghost1();
uint32_t getHeightvulnghost1();
uint32_t getBytePerPixelvulnghost1();
const uint8_t *getPixelDatavulnghost1();
uint32_t getWidthvulnghost2();
uint32_t getHeightvulnghost2();
uint32_t getBytePerPixelvulnghost2();
const uint8_t *getPixelDatavulnghost2();
