#ifndef PINCONFIG_H
#define PINCONFIG_H

#define PIN_NUM_LEDS_MOSI         GPIO_NUM_23
#define PIN_NUM_LEDS_CLK          GPIO_NUM_18

#define PIN_NUM_DHT_DATA          GPIO_NUM_5

#define PIN_NUM_ESP_TX_MHZ19B_RX  GPIO_NUM_17
#define PIN_NUM_ESP_RX_MHZ19B_TX  GPIO_NUM_16

#define PIN_NUM_MQ1310            GPIO_NUM_2

#define PIN_NUM_SD_CS             GPIO_NUM_4

#define PIN_NUM_DISPLAY_CS        GPIO_NUM_15
#define PIN_NUM_DISPLAY_MOSI      GPIO_NUM_13
#define PIN_NUM_DISPLAY_MISO      GPIO_NUM_12
#define PIN_NUM_DISPLAY_SCK       GPIO_NUM_14
#define PIN_NUM_DISPLAY_DATA_CMD  GPIO_NUM_27
#define PIN_NUM_DISPLAY_RESET     GPIO_NUM_26
#define PIN_NUM_DISPLAY_BACKLIGHT GPIO_NUM_32

#define PIN_NUM_TOUCH_MISO        PIN_NUM_DISPLAY_MISO
#define PIN_NUM_TOUCH_MOSI        PIN_NUM_DISPLAY_MOSI
#define PIN_NUM_TOUCH_CLK         PIN_NUM_DISPLAY_SCK
#define PIN_NUM_TOUCH_CS          GPIO_NUM_25
#define PIN_NUM_TOUCH_IRQ         GPIO_NUM_33

#define PIN_NUM_PHOTO_RESITOR     GPIO_NUM_35
#define ADC_CHANNEL_PHOTO_RESITOR ADC1_CHANNEL_7
#define PIN_NUM_IR_OUTPUT_IRQ     GPIO_NUM_34

#endif
