plevel1:
	python3 main.py -i pacmanlevel1.csv -o ../../firmware/main/maps/pacmanlevel1.map -p ../../firmware/main/maps/pacmanlevel1.cpp

mainmap:
	python3 main.py -i mainmap.csv -o ../../firmware/main/maps/mainmap.map -p ../../firmware/main/maps/mainmap.cpp 
