#pragma once
uint32_t getWidthbarrier();
uint32_t getHeightbarrier();
uint32_t getBytePerPixelbarrier();
const uint8_t *getPixelDatabarrier();
uint32_t getWidthbonus();
uint32_t getHeightbonus();
uint32_t getBytePerPixelbonus();
const uint8_t *getPixelDatabonus();
uint32_t getWidthexplosion();
uint32_t getHeightexplosion();
uint32_t getBytePerPixelexplosion();
const uint8_t *getPixelDataexplosion();
uint32_t getWidthinvader1a();
uint32_t getHeightinvader1a();
uint32_t getBytePerPixelinvader1a();
const uint8_t *getPixelDatainvader1a();
uint32_t getWidthinvader1();
uint32_t getHeightinvader1();
uint32_t getBytePerPixelinvader1();
const uint8_t *getPixelDatainvader1();
uint32_t getWidthinvader2a();
uint32_t getHeightinvader2a();
uint32_t getBytePerPixelinvader2a();
const uint8_t *getPixelDatainvader2a();
uint32_t getWidthinvader2();
uint32_t getHeightinvader2();
uint32_t getBytePerPixelinvader2();
const uint8_t *getPixelDatainvader2();
uint32_t getWidthinvader3a();
uint32_t getHeightinvader3a();
uint32_t getBytePerPixelinvader3a();
const uint8_t *getPixelDatainvader3a();
uint32_t getWidthinvader3();
uint32_t getHeightinvader3();
uint32_t getBytePerPixelinvader3();
const uint8_t *getPixelDatainvader3();
uint32_t getWidthinvaderexplosion();
uint32_t getHeightinvaderexplosion();
uint32_t getBytePerPixelinvaderexplosion();
const uint8_t *getPixelDatainvaderexplosion();
uint32_t getWidthinvader_shot();
uint32_t getHeightinvader_shot();
uint32_t getBytePerPixelinvader_shot();
const uint8_t *getPixelDatainvader_shot();
uint32_t getWidthplayer();
uint32_t getHeightplayer();
uint32_t getBytePerPixelplayer();
const uint8_t *getPixelDataplayer();
uint32_t getWidthplayer_explosion1a();
uint32_t getHeightplayer_explosion1a();
uint32_t getBytePerPixelplayer_explosion1a();
const uint8_t *getPixelDataplayer_explosion1a();
uint32_t getWidthplayer_explosion1();
uint32_t getHeightplayer_explosion1();
uint32_t getBytePerPixelplayer_explosion1();
const uint8_t *getPixelDataplayer_explosion1();
uint32_t getWidthplayer_explosion();
uint32_t getHeightplayer_explosion();
uint32_t getBytePerPixelplayer_explosion();
const uint8_t *getPixelDataplayer_explosion();
uint32_t getWidthplayer_shot();
uint32_t getHeightplayer_shot();
uint32_t getBytePerPixelplayer_shot();
const uint8_t *getPixelDataplayer_shot();
